version: "2.2"
services:

  elasticsearch:
    build:
      context: ./build
      dockerfile: Dockerfile-elasticsearch

    container_name: elasticsearch

    ports:
      - "9200:9200"
      - "9300:9300"

    # environment:
    #   - discovery.type=single-node

    volumes:
      - ./data:/data

      # elasticsearch data
      - esdata:/var/lib/elasticsearch

      # elasticsearch config
      - ./config/elasticsearch/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml

      # keystore
      # - ./config/elasticsearch/elasticsearch.keystore:/etc/elasticsearch/elasticsearch.keystore

      # certificates
      # - ./config/elasticsearch/elastic-stack-ca.p12:/etc/elasticsearch/certs/elastic-stack-ca.p12
      # - ./config/elasticsearch/elastic-certificates.p12:/etc/elasticsearch/certs/elastic-certificates.p12

    networks:
      - esnet

  kibana:
    image: kibana:7.3.1

    container_name: kibana

    ports:
      - "5601:5601"

    volumes:
      - ./data:/data

      # kibana config
      - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

      # keystore
      - ./config/kibana/kibana.keystore:/usr/share/kibana/data/kibana.keystore

    networks:
      - esnet


  logstash:
    build:
      context: ./build
      dockerfile: Dockerfile-logstash

    container_name: logstash

    expose:
      - "5044"

    volumes:
      - ./data:/data

      # logstash config
      - ./config/logstash/logstash.yml:/etc/logstash/logstash.yml
      - ./config/logstash/pipelines.yml:/etc/logstash/pipelines.yml
      - ./config/logstash/conf.d:/etc/logstash/conf.d

      # keystore
      - ./config/logstash/logstash.keystore:/etc/logstash/logstash.keystore

      # filebeat config
      - ./config/filebeat/filebeat.yml:/etc/filebeat/filebeat.yml


    networks:
      - esnet

volumes:
  esdata:
    driver: local

networks:
  esnet:
